### ISSUE TITLE
selecting all sub items when selecting the parent.

### ISSUE THREAD

**Issue by harishksoft** [erhanfirat/combo-tree#10]
@kirlisakal is it possible to select all the sub-items when selecting the parent item? something like this https://www.jqueryscript.net/demo/Collapsible-Tree-View-Checkboxes-jQuery-hummingbird/

and need to get all selected checkbox ids in the getselecteditem variable

**Comment by sancel22** [comment]
@harishksoft while waiting for this update, For the meantime I'm doing it externally.

```
            $.each(JSON.parse(target_keys), function(index, target) {
                $('span[data-id="'+target+'"]').on('click', function() {
                    var checkBoxes = $(this).parent().find('ul input:checkbox');
                    var isCheck = $(this).find('input').prop('checked');
                    $.each(checkBoxes, function(i, cTarget) {
                        if (isCheck !== $(cTarget).prop('checked')) {
                            $(cTarget).parent().click();
                        }
                    });
                });
            })
```

**Comment by erhanfirat** [comment]
You can achieve this by setting `cascadeSelect` option to true. Thanks...
