### ISSUE TITLE
Overflow hidden

### ISSUE THREAD

**Issue by essencient** [erhanfirat/combo-tree#12]
When the combotreedropdowncontainer has overflow set to hidden so that the you can't scroll if data loaded doesn't all fit. Can't see where to change this.

**Comment by erhanfirat** [comment]
Can you share screen pic?

**Comment by erhanfirat** [comment]
expired!

**Comment by pnbecker** [comment]
You might have run into https://bugs.jquery.com/ticket/12630 if you used an old version of JQuery. There is a simple solution: in styles.css `overflow-y:auto;` is set on `.comboTreeDropDownContainer`. Just add `!important` and it works like a charm.
