### ISSUE TITLE
How to get data-id from selected option

### ISSUE THREAD

**Issue by fitra68** [erhanfirat/combo-tree#17]
when user select an option from drop down list, how to get the data-id from that correspond selected option? thanks.

**Comment by Muthukumar-Kannan** [comment]
> when user select an option from drop down list, how to get the data-id from that correspond selected option? thanks.

Hi @fitra68 ,
I'm facing the same issue. did you find how to get the select id, if yes please help me out?

**Comment by kirlisakal** [comment]
You can use 

`var selectedIds = comboTree1.getSelectedItemsId();`

Do you mean at the moment user event fired?

**Comment by erhanfirat** [comment]
Update: 

`comboTree1.onChange(function(){ 
  console.log(comboTree1.getSelectedIds());
})`

enjoy it...
