### ISSUE TITLE
Start collapsed 

### ISSUE THREAD

**Issue by alienwarebusan** [erhanfirat/combo-tree#18]
Hi there, thanks for the great plugin.
I'm using ComboTree for quite a large data set. I would like the tree to be initialized collapsed and to allow users to expand categories.

Please advise me how to best do this.
Thank you

**Comment by erhanfirat** [comment]
Hi @alienwarebusan 

With new version, you can set `collapse` option to true when initialize it...

Thanks...

**Comment by techiesalman** [comment]
@erhanfirat sir `collapse: true` doesn't work. Is there any other way around for this?
