### ISSUE TITLE
Popup list dissapeares if I change the selection manualy

### ISSUE THREAD

**Issue by HolyOne** [erhanfirat/combo-tree#21]
I test it here,

https://www.jqueryscript.net/demo/Drop-Down-Combo-Tree/

I select something from the 3rd combo box. I change the textbox content with keyboard, click enter. The list is now disapeared

**Comment by erhanfirat** [comment]
Hi,

If you mean single select combo box, it is expected behaviour to close dropdown after making selection.  Cuz, it is single selection mode, and you are done once select it.
If you want to change selection, then you can click down arrow to open it again... 

Enjoy it...

**Comment by HolyOne** [comment]
No it is not expected behavior.
I think it should provide a hint or have a clear selection button somewhere etc

**Comment by erhanfirat** [comment]
İlk defa GitHub da bu kadar ahmakça bir yoprum görüp, bu ahmağa laf mı anlatıcam diye sildim... 
Sonra yazanın adına bir baktım, Aytek Üstündağ... Siz nerden türediniz...
