### ISSUE TITLE
Filter functionality doesn't seem to work

### ISSUE THREAD

**Issue by annupa** [erhanfirat/combo-tree#22]
I am getting error as attached while performing a filter. Tree is being loaded correctly and selection, deselection works fine. Search text given is 6 . Have added comboTreePlugin.js & icontains.js. Please help.
![Combo Tree Error](https://user-images.githubusercontent.com/59667506/72016028-f052d200-3230-11ea-81c1-92f5c8e59bdd.jpg)

<input type="text" id="chkBoxTree" placeholder="Select">
$('#chkBoxTree').comboTree({
                            source: SampleJSONData,
                            isMultiple: true
                           });

**Comment by erhanfirat** [comment]
I will check ASAP.

Thanks...

**Comment by erhanfirat** [comment]
It is fixed on v1.2.1.

**Comment by annupa** [comment]
Thank you. Your help is greatly appreciated.
