### ISSUE TITLE
getSelectedItemsTitle & getSelectedItemsId errors

### ISSUE THREAD

**Issue by chyasif** [erhanfirat/combo-tree#23]
Following functions are not working . Would please submit example of following two functions  in your sample file?

var selectedTitles = comboTree1.getSelectedItemsTitle();
var selectedIds = comboTree1.getSelectedItemsId();

Regards

Asif

**Comment by rodnorth** [comment]
If you are using the latest release the function names have changed to:-

getSelectedIds() and getSelectedNames().

The first one is working OK for me - haven't needed the other one.

Erhan - perhaps you can update the readme when you get a chance :-)

**Comment by erhanfirat** [comment]
@rodnorth & @chyasif 
Actually, I have updated readme just after clearified method names.

https://github.com/erhanfirat/combo-tree/blob/master/README.md

Cheers...
