### ISSUE TITLE
How to setValues(check the items) dynamically using jQuery

### ISSUE THREAD

**Issue by SivaSakthi07** [erhanfirat/combo-tree#8]
Is there any option to setValues like 

$('#MenuTree').val(numbersArray) or 	$('#MenuTree').comboTree('setValues',numbersArray);

...
I need this to show previously selected values in my edit page....

**Comment by erhanfirat** [comment]
Hi @SivaSakthi07 

You can use `setSelection` method. Please read documentation about it.

Thanks..
