### ISSUE TITLE
reset 

### ISSUE THREAD

**Issue by mikialey** [erhanfirat/combo-tree#9]
hi. i would like reset clear but i have bug. i try it.
compartments is array with all ids 

compartments.forEach(function(element) {
          $(`input[data-id="${element}"]`).prop('checked',false);
        });
        compartments = new Array();
        $('#form_compartments').val('');

bug keep in memory the choice 

thanks

**Comment by kirlisakal** [comment]
Select All and Deselect All functions will be added, soon.

**Comment by erhanfirat** [comment]
You can user `clearSelection `method. Thanks...
